### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by bad5ect0r** [VFXGamer/PhishBuster#1]
https://github.com/VFXGamer/PhishBuster/blob/0a533059168cfeba7eebac4ae85dc8db5d853421/app.py#L44

I did not install this but from static code review, I can tell this is a likely SQL injection vulnerability.

**Comment by VFXGamer** [comment]
SQL Injection should not be possible as if you see https://github.com/VFXGamer/PhishBuster/blob/0a533059168cfeba7eebac4ae85dc8db5d853421/app.py#L41
When you will try for a sql injection attack the `phishbuster.py (imported as pb)` would be called, it will give an error which will result in <br>
**Internal Server Error<br>
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.**<br>
Thank You for bringing my attention to this. I will soon make changes for proper execution of this error. 
Once again
Thank You
