### ISSUE TITLE
Adding LICENCE section under README File.

### ISSUE THREAD

**Issue by Pradumnasaraf** [VFXGamer/PhishBuster#13]
@VFXGamer plz assign

**Comment by Pradumnasaraf** [comment]
I still want to it :) @VFXGamer

**Comment by VFXGamer** [comment]
You can do it. But I won't label your PR as "hacktoberfest-accepted".

**Comment by VFXGamer** [comment]
> ![Screenshot 2021-10-07 073329](https://user-images.githubusercontent.com/51878265/136308844-908219b7-c479-452f-a10a-45f482036a33.png) The report link is also not working or either broken or unreachable. I think need to replace the link with , https://phishbuster-web.herokuapp.com/reports @VFXGamer

It redirects to localhost currently. Yea sure go ahead.
