### ISSUE TITLE
Reports Tab not Responsive for Mobile

### ISSUE THREAD

**Issue by VFXGamer** [VFXGamer/PhishBuster#19]
**Describe the bug**
Non responsive table section in reports.

**To Reproduce**
1. Go to '[reports.](https://phishbuster-web.herokuapp.com/reports)'
2. If you are on phone you can see it.

If you are on PC:
1. Go to '[reports.](https://phishbuster-web.herokuapp.com/reports)'
2. Using google dev tools change it to mobile preview.

**Screenshots**
*Note: White lines are there because the image is not cropped properly.*
![Responsive Problem](https://user-images.githubusercontent.com/62838631/137582983-9c721621-8413-485f-ad33-ca0b6817fd63.jpg)

**Comment by abritpal** [comment]
HI!, can you assign me this issue this thing

**Comment by abritpal** [comment]
hey! I'm getting this error while pushing 
`
remote: Permission to VFXGamer/PhishBuster.git denied to abritpal.
fatal: unable to access 'https://github.com/VFXGamer/PhishBuster.git/': The requested URL returned error: 403
`
what should I do?
