### ISSUE TITLE
Empty Error

### ISSUE THREAD

**Issue by VFXGamer** [VFXGamer/PhishBuster#3]
When the [/reports](https://phishbuster-web.herokuapp.com/reports) has no sites in the table, it show database connection error.
This error is not because of connection issue it is just an issue which can be fixed using python code.

![reports empty error](https://user-images.githubusercontent.com/62838631/135715111-88e232db-e218-4718-a4ee-8d76730ca435.jpg)

Do let me know if you need more info about the error.
You can visit [PhishBuster](https://phishbuster-web.herokuapp.com/reports) and see the error in action.

**Comment by ry-v1** [comment]
Hello @VFXGamer , Submitted pull request #5 to fix issue  "Open Empty Error" #3. There are still few checks are failing but those are not because of my changes. Let me know if that needs to be fixed.

**Comment by VFXGamer** [comment]
If you can fix them too it would be great.

**Comment by ry-v1** [comment]
> If you can fix them too it would be great.

@VFXGamer - Fixed all, except one "Redefining built-in 'id' " , that might require changes to templates, so didn't do. Please check if it looks okay.

**Comment by VFXGamer** [comment]
#5  
This Issue is resolved.
