### ISSUE TITLE
Add Docker Support

### ISSUE THREAD

**Issue by DanBrown47** [VFXGamer/PhishBuster#6]
**Is your feature request related to a problem? Please describe.**
This feature will standardize build environment and increase ease to setup

**Describe the solution you'd like**
Add Dockerfile which can easily setup the server within few seconds.

**Describe alternatives you've considered**
This contribution can also speed up the workflow time line.

**Comment by VFXGamer** [comment]
Good Idea.

**Comment by s-surineni** [comment]
@VFXGamer I'd like to help with this issue

**Comment by DanBrown47** [comment]
While going around setting up environment variables for the app, I came across

`app.config['MYSQL_DATABASE_PASSWORD'] = os.environ['password']`

To make the application more flexible we can add .env files along and use [`python-dotenv`](https://pypi.org/project/python-dotenv/) along with standard OS library, so that developers can quickly make up just by creating a dot env file,

Also I am creating an .env.example for developers to get an headstart for setting up the env variables.

**Comment by DanBrown47** [comment]
@s-surineni I have completed coding the solution for the issue, Please feel free to enhance my Pull request once I create one.

**Comment by VFXGamer** [comment]
You can use the phishbuster sql file for database setup.
