### ISSUE TITLE
All Github link should be open in new tab

### ISSUE THREAD

**Issue by Jaspreet099** [VFXGamer/PhishBuster#9]
**Is your feature request related to a problem? Please describe.**
ALl the Github links should be open in new tab because at the same time I see website and github.

**Describe the solution you'd like**
I will add target="_blank" in links 

**Additional context**
![image](https://user-images.githubusercontent.com/75212002/135877737-ccdfb008-153e-41d3-8b7a-fa666f9c9601.png)

You can assign this Issue to me:)

**Comment by mogiiee** [comment]
please add more hacktoberfest labeled issues ... more features, a connection to a db or anything of that sort
